<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>lock</artifactId>
        <groupId>com.github.houbb</groupId>
        <version>1.7.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lock-test</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>lock-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>lock-spring</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>lock-mysql</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>test-spring</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>slf4j-common</artifactId>
            <version>1.0.0</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.1.11</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.11</version>
        </dependency>
    </dependencies>

</project>
