<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>lock</artifactId>
        <groupId>com.github.houbb</groupId>
        <version>1.6.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>lock-core</artifactId>
    <description>The core lock implements.</description>

    <dependencies>
        <!--============================== SELF ==============================-->
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>lock-api</artifactId>
        </dependency>

        <!--============================== INTER ==============================-->
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>id-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>wait</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>heaven</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>log-integration</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>common-cache-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>redis-config-core</artifactId>
        </dependency>

    </dependencies>

</project>
